# Generated by Django 3.2.4 on 2021-06-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_footer_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=500)),
                ('email_id', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('web_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecome.website_settings')),
            ],
        ),
        migrations.CreateModel(
            name='website_content_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_image1', models.ImageField(upload_to='content_image')),
                ('ban_image2', models.ImageField(upload_to='content_image')),
                ('ban_image3', models.ImageField(upload_to='content_image')),
                ('ban_image4', models.ImageField(upload_to='content_image')),
                ('ban_image5', models.ImageField(upload_to='content_image')),
                ('ban_image6', models.ImageField(upload_to='content_image')),
                ('web_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecome.website_settings')),
            ],
        ),
        migrations.CreateModel(
            name='website_banner_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_image1', models.ImageField(upload_to='banner')),
                ('ban_image2', models.ImageField(upload_to='banner')),
                ('web_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecome.website_settings')),
            ],
        ),
    ]
