# Generated by Django 3.2.4 on 2021-06-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecome', '0002_website_banner_image_website_content_image_website_footer_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(max_length=500)),
                ('web_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecome.website_settings')),
            ],
        ),
    ]
