# Generated by Django 3.2.4 on 2021-06-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecome', '0003_website_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_banner_image',
            name='ban_image3',
            field=models.ImageField(blank=True, default='banner/download.jpg', null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='website_banner_image',
            name='ban_image1',
            field=models.ImageField(blank=True, default='banner/download.jpg', null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='website_banner_image',
            name='ban_image2',
            field=models.ImageField(blank=True, default='banner/download.jpg', null=True, upload_to='banner'),
        ),
    ]
